# Generated by Django 2.2.4 on 2019-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(default='yo')),
            ],
        ),
        migrations.CreateModel(
            name='random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran', models.TimeField()),
                ('go', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
