# Generated by Django 2.2.4 on 2019-08-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_trying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random',
            name='go',
            field=models.TextField(null=True),
        ),
    ]
