# Generated by Django 2.2.4 on 2019-08-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_trying', '0002_auto_20190805_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random',
            name='go',
            field=models.TextField(blank=True, null=True),
        ),
    ]
