# Generated by Django 2.2.4 on 2019-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_trying', '0003_auto_20190805_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='why',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=200, null=True),
        ),
    ]
