# Generated by Django 2.2.4 on 2019-08-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_trying', '0004_random_why'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random',
            name='go',
        ),
    ]
