# Generated by Django 2.2.4 on 2019-08-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_related', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='summary',
            field=models.TextField(default='random_stuff'),
        ),
    ]
